web:
  build: .
  ports:
    - "8080:80"
    - "50022:22"
  volumes:
    - ./src/core:/var/www/drupal/core
    - ./src/modules:/var/www/drupal/modules
    - ./src/profiles:/var/www/drupal/profiles
    - ./src/themes:/var/www/drupal/themes
  links:
    - db
db:
  image: mysql
  environment:
    MYSQL_DATABASE: drupal
    MYSQL_USER: drupal
    MYSQL_PASSWORD:
    MYSQL_ROOT_PASSWORD:
