web:
  build: .
  ports:
    - "8080:80"
    - "50022:22"
  links:
    - db
db:
  image: mysql
  environment:
    MYSQL_DATABASE: drupal
    MYSQL_USER: drupal
    MYSQL_PASSWORD: drupal
    MYSQL_ROOT_PASSWORD: drupi
